<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <NuGetAudit>false</NuGetAudit>
    </PropertyGroup>
    <ItemGroup>
        <None Include="index.html" />
        <Compile Include="Types.fs" />
        <Compile Include="Model.fs" />
        <Compile Include="Msg.fs" />
        <Compile Include="Canvas/BitCanvas.fs" />
        <Compile Include="App.fs" />
        <Compile Include="App.test.fs" />
        <Compile Include="Main.fs" />
    </ItemGroup>
    <Import Project="..\.paket\Paket.Restore.targets" />
</Project>
